version: '3.8'
services:
  web:
    image: flask-sql-api:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - "5000:5000"
