version: '3.8'
services:
  web:
    build:
      context: ./flask
      dockerfile: Dockerfile 
    ports:
      - "5000:80" 
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
